version: 2 

sources:
- name: github
  database: analytics-engineers-club
  schema: github
  tables:
    - name: pull_request
      columns:
        - name: id
          description: "this is NOT the pull request number"
          tests: 
            - unique
            - not_null
    - name: issue
      description: "This table contains both issues and pull requests"
      columns:
        - name: id
          tests: 
            - unique
            - not_null
    - name: issue_merged
      columns:
        - name: issue_id
          tests: 
            - unique
            - not_null
    - name: repository
      columns:
        - name: id
          tests: 
            - unique
            - not_null
- name: advanced_dbt_examples
  database: analytics-engineers-club
  schema: advanced_dbt_examples
  tables:
      - name: form_events
      - name: favorite_ice_cream_flavors
